[WIP]devise_flash_messages_feature
nakamra/chat-space pull request #11
Opened 2017-01-20 08:17 UTC by nakamra

2017-01-20 16:14 UTC, nakamra commented
![2017-01-21 1 11 33 2](https://cloud.githubusercontent.com/assets/25055629/22156514/edf4cd48-df76-11e6-86f2-503df539015e.png)

2017-01-20 16:19 UTC, nakamra commented
<img width="1280" alt="2017-01-21 1 17 27" src="https://cloud.githubusercontent.com/assets/25055629/22156646/995fbc10-df77-11e6-8c7c-f053100085c8.png">

2017-01-20 16:19 UTC, nakamra commented
<img width="1280" alt="2017-01-21 1 17 45" src="https://cloud.githubusercontent.com/assets/25055629/22156656/a51be7b8-df77-11e6-9d4b-12540b3a48b3.png">

2017-01-20 16:19 UTC, nakamra commented
<img width="1280" alt="2017-01-21 1 17 20" src="https://cloud.githubusercontent.com/assets/25055629/22156678/b70586f0-df77-11e6-9fe2-40bfd4630acd.png">

2017-01-20 16:20 UTC, nakamra commented
<img width="1280" alt="2017-01-21 1 15 40" src="https://cloud.githubusercontent.com/assets/25055629/22156688/c732a9b8-df77-11e6-89a9-a486422ca6f6.png">

2017-01-21 02:18 UTC, DaikiInaba commented on app/views/layouts/application.html.haml
> +        = alert
この書き方をしてしまいますと異なる種類のフラッシュを追加する度に同様の記述を加える必要が有るので、汎用的な書き方をしたほうがよろしいですね！

2017-01-21 03:09 UTC, nakamra commented on app/views/layouts/application.html.haml
> +        = alert
each で書き換え修正しました。

2017-01-21 03:13 UTC, takebnn26 requested changes

2017-01-21 03:13 UTC, takebnn26 commented on app/views/layouts/application.html.haml
> +    .top-bar
かなり綺麗になりましたね！
こちらのフラッシュメッセージの部分だけ部分テンプレート化するとさらに綺麗です！

2017-01-21 03:13 UTC, takebnn26 commented on app/views/layouts/application.html.haml
> +        %div{class: "alert alert--#{key}"}
こちらはさらに便利なメソッドで綺麗に書くことができるので調べて試してみましょう

2017-01-21 03:23 UTC, nakamra commented on app/views/layouts/application.html.haml
> +    .top-bar
新たに_flash-message.scssを作り application.scss にimportしました。

2017-01-21 04:07 UTC, nakamra commented on app/views/layouts/application.html.haml
> +        %div{class: "alert alert--#{key}"}
親要素の.top-barを消しeachの中で親要素のクラス指定をしました

2017-01-21 04:09 UTC, DaikiInaba commented on app/views/layouts/_flash-messages.html.haml
> +  - else
条件分岐必要でしょうか？
また必要だとしてもifよりふさわしい書き方がありますね！

2017-01-21 04:16 UTC, nakamra commented on app/views/layouts/_flash-messages.html.haml
> +  - else
条件分岐は消しました。

2017-01-21 04:23 UTC, tomoki0120 commented
LGTMです！

2017-01-21 04:28 UTC, merged