[WIP]Feature ChatSpaceFront
nakamra/chat-space pull request #5
Opened 2017-01-16 04:43 UTC by nakamra

# What
chat-spaceのフロント実装

# Why
機能を実装する前にフロントをまず実装するため

2017-01-18 09:32 UTC, Maverick1211 commented on app/assets/stylesheets/_chat-main.scss
> +    .chat-header__users {
&使いましょう

2017-01-18 09:35 UTC, nakamra commented
<img width="1280" alt="2017-01-18 18 32 46" src="https://cloud.githubusercontent.com/assets/25055629/22058577/c03e46c0-ddac-11e6-9716-15c8197a3beb.png">
すみません。スクリーンショット忘れてました。

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/_chat-main.scss
> +  .chat-header--left {
&記法使いましょう！

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/_chat-main.scss
> +      padding-left:20px;
まとめて
padding: 0 20px;
と書けます！

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/_chat-main.scss
> +      color: #38AEF0;
変数化しましょう！

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/_chat-side.scss
> +      margin:15px 0 15px 3px;
:の後ろにスペース入れましょう！

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/_chat-side.scss
> +    padding: 20px 20px;
padding: 20px;
でいいですね

2017-01-18 09:38 UTC, DaikiInaba commented on app/assets/stylesheets/application.scss
> +  }
application.scssはimportのみにして、_base.scssや_common.scssのようなファイルを作ってそこに移しましょう！

2017-01-18 09:38 UTC, DaikiInaba commented on config/routes.rb
> +  get 'messages' => 'messages#index'
resources使用しましょう！

2017-01-19 02:21 UTC, takebnn26 requested changes

2017-01-19 02:21 UTC, takebnn26 commented on app/assets/stylesheets/_base.scss
> +@import "./variable";
こちらapplication.scssでmportしてしまえばその後の複数のファイルで使えます！

2017-01-19 02:21 UTC, takebnn26 commented on app/assets/stylesheets/_chat-main.scss
> +@import "./variable";
こちらapplication.scssでmportしてしまえばその後の複数のファイルで使えます！

2017-01-19 02:21 UTC, takebnn26 commented on app/assets/stylesheets/_chat-main.scss
> +@import "./clearfix";
こちらapplication.scssでmportしてしまえばその後の複数のファイルで使えます！

2017-01-19 02:21 UTC, takebnn26 commented on app/assets/stylesheets/_chat-side.scss
> +@import "./clearfix";
こちらapplication.scssでmportしてしまえばその後の複数のファイルで使えます！

2017-01-19 02:21 UTC, takebnn26 commented on app/assets/stylesheets/_base.scss
> +  color: #fff;
二回以上使われる色は全て変数化して使いまわしましょう！

2017-01-19 02:40 UTC, merged